# Generated by Django 3.1.6 on 2021-02-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Write your todo title', max_length=100, verbose_name='Todo title')),
                ('description', models.TextField(help_text='Write your todo description', verbose_name='Todo description')),
                ('created_date', models.DateTimeField(auto_now=True, help_text='Todo created date and time', verbose_name='Created Date')),
                ('deadline_date', models.DateTimeField(help_text='Todo deadline date and time', verbose_name='Deadline date and time')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
